#For focker to read nad execute the mongo-init.js filem the database must not already exist.
#That is, the mongo-init.js file is only exexuted the one time, on newwly initialized databases

version: '4.0'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    #restart always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db-data:/data/db
    container_name: local-mongo

  mongo-express:
    image: mongo-express
    #restart always fixes mongo network error when mongodb is not ready when mongo-express starts
    ports:
      - "8081:8081"
    environment:
      - MF_CONFIG_MONGODB_ADMINUSERNAME=admin
      - MF_CONFIG_MONGODB_ADMINPASSWORD=password
      - MF_CONFIG_MONGODB_SERVER=mongodb
    container_name: local-mongoexpress
    depends_on:
      - mongodb

#volumes