# ----------------------------------------------------------------------------------------------------------------
# create networks
# -p give me a folder, up brings up all the containers
# 1. docker-compose -p comp3095-microservices-ecommerce -f docker-compose-single.yml up -d
#     -- This command will start the containers in detached made without rebuilding the images (if they exist)
#
# 2. docker-compose -p comp3095-microservices-ecommerce -f docker-compose-single.yml up -d --build
#     -- This command force the rebuild of all images, even if already exist, before starting the containers
# ----------------------------------------------------------------------------------------------------------------

version: "3.9"

services:

  product-service:
    image: product-service
    ports:
      - "8084:8084"
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service-manual
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  mongodb:
    image: mongo
    container_name: mongodb-manual
    environment:
      - MONGO_INIT_ROOT_USERNAME=admin
      - MONGO_INIT_ROOT_PASSWORD=password      - MONGO_INIT_ROOT_PASSWORD=password
      - MONGO_INIT_ROOT_SERVER=mongodb
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #    restart: unless-stopped
    #    command: mongod --auth
    networks:
      - spring

  mongo-express:
    image: mongo-express
    container_name: mongo-express-manual
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - spring

volumes:
  mongodb:
    driver: local # use local driver for persisting data on the host machine

networks:
  spring:
    driver: bridge # bridge network allows isolated communication between containers
